### ISSUE TITLE
question : why does this not work 

### ISSUE THREAD

**Issue by roelof1967** [landau/hapi-react#3]
Hello, 

Im trying to follow this tutorial :  http://facebook.github.io/react/docs/tutorial.html
But when I run it , I see this error message : 

~~~
transforming /home/action/workspace/hapi_ecommerce/templates/about_us.jsx to JSX: Error: Parse Error: Line 14: Unexpected token :: Error transforming /home/action/workspace/hapi_ecommerce/templates/about_us.jsx to JSX: Error: Parse Error: Line 14: Unexpecte
d token : 

~~~

My code can be found here : https://github.com/roelof1967/hapi_ecommerce

**Comment by landau** [comment]
You're using the engine incorrectly. Whatever template `reply.view` is called on must `export` a `React` class. 

https://github.com/roelof1967/hapi_ecommerce/blob/master/templates/about_us.jsx is `html`.

**Comment by roelof1967** [comment]
changed it as you said but still the same error.

**Comment by landau** [comment]
Hard to say what the problem is without seeing code. I've used this in production code used in the same fashion as your hapi server

**Comment by roelof1967** [comment]
I will give you the code again. The code can be found here :  https://github.com/roelof1967/hapi_ecommerce

**Comment by landau** [comment]
Hmm. I don't see any view code at all now.
