### ISSUE TITLE
Support react 0.14

### ISSUE THREAD

**Issue by sriprabha** [landau/hapi-react#5]
When will hapi-react updated to work with React 0.14?

**Comment by landau** [comment]
No, peer deps are set to 0.12-0.13. I will address this. Thanks!

https://github.com/landau/hapi-react/blob/master/package.json#L31

**Comment by hydrotik** [comment]
Any update on this? :)

**Comment by landau** [comment]
I've been a bit busy. Feel free to create a PR if you are running impatient. I'll try to sneak this work in today if I can.

**Comment by landau** [comment]
this is done.
